
import type { Metadata } from "next";
import "./globals.css";
import { cormorantInfant, geistMono, geistSans, hurricane, lato, lavishlyYours, nunito, poiretOne, squarePeg, ysabeau } from "@/utils/fonts";
import Footer from "@/components/Footer";
import RootBody from "@/components/RootBody";
import Header from "@/components/Header";
import IconsInfosList from "@/components/IconsInfosList";
import MenuResponsive from "@/components/responsive/MenuResponsive";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html 
      lang="fr" 
      className={`${poiretOne.variable} ${cormorantInfant.variable} ${nunito.variable} ${squarePeg.variable} ${ysabeau.variable} ${lato.variable} ${hurricane.variable} ${lavishlyYours.variable}`} 
    >
      <body className={`${geistSans.variable} ${geistMono.variable} relative antialiased min-h-screen w-full overflow-x-hidden`}>
        <Header/>
        <div className="relative">
          <MenuResponsive/>
          <IconsInfosList/>
        </div>
        <RootBody>
          {children}
        </RootBody>
        <Footer/>
      </body>
    </html>
  );
}
